version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Paris"
    assignees:
      - "Ziedelth"
    reviewers:
      - "Ziedelth"
    groups:
      ktor:
        patterns:
          - "*ktor*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Paris"
    assignees:
      - "Ziedelth"
    reviewers:
      - "Ziedelth"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Paris"
    assignees:
      - "Ziedelth"
    reviewers:
      - "Ziedelth"