name: 'Setup Dependencies'
description: 'Install Java and WebP'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        java-version: 25
        distribution: 'corretto'
        cache: gradle

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y webp
