version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  site:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: site
    ports:
      - "8082:8082"
    environment:
      - PORT=8082

  admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: admin
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  jobs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: jobs
