package fr.shikkanime.entities.enums

enum class Genre(vararg aliases: String) {
    ACTION("action"),
    ADOLESCENCE("adolescence"),
    ADVENTURE("aventure"),
    ALCOHOL("alcool"),
    ALIENS_EXTRA_TERRESTRIALS("aliens / extra-terrestres"),
    ANGELS("anges"),
    ANIMALS("animaux"),
    BDSM("bdsm"),
    BEAST_MAN("homme-bête"),
    CLUB("club"),
    COMEDY("comédie"),
    CRIME("crime"),
    CYBORGS("cyborgs"),
    DAILY("quotidien"),
    DEATH("mort"),
    DEMONS("démons"),
    DISABILITY("handicap"),
    DRAGONS("dragons"),
    DRAMA("drame"),
    ECCHI("ecchi"),
    ELF("elfe"),
    FAMILY("famille"),
    FANTASTIC("fantastique"),
    FANTASY("fantasy"),
    FIGHTING("combat"),
    FIREFIGHTER("pompier"),
    FOOTBALL("football"),
    FRIENDSHIP("amitié"),
    FUTURE("futur"),
    GAME("jeux"),
    GASTRONOMY("gastronomie"),
    GHOSTS("fantômes"),
    GODS_GODDESSES("dieux / déesses"),
    GORE("gore"),
    HAREM("harem"),
    HISTORY("historique"),
    HOMOSEXUALITY("homosexualité"),
    HORROR_SCARY("horreur / épouvante"),
    ISEKAI("isekai"),
    INVERTED_HAREM("harem inversé"),
    KYUDO("kyūdō"),
    LEARNING("apprentissage"),
    LGBT_PLUS("lgbt+"),
    LIES("mensonges"),
    LOVE("amour"),
    MAGIC("magie"),
    MAGICAL_GIRL("magical girl"),
    MAHJONG("mahjong"),
    MARTIAL_ARTS("arts martiaux"),
    MEDICINE("médecine"),
    MEDIEVAL("médiéval"),
    MILITARY("militaire"),
    MONSTER_GIRL("monster girl"),
    MONSTERS("monstres"),
    MURDER("assassinat"),
    MUSIC("musique"),
    MYSTERY("mystère"),
    NEKKETSU("nekketsu"),
    NOSTALGIA("nostalgie"),
    OTHER_WORLD("autre monde"),
    PARANORMAL("paranormal"),
    PARODY("parodie"),
    PIRATES("pirates"),
    POLYGAMY("polygamie"),
    POST_APOCALYPTIC("post-apocalyptique"),
    PSYCHIC_POWERS("Pouvoirs psychiques"),
    PSYCHOLOGY("Psychologique"),
    RELIGION("religion"),
    REINCARNATION_TRANSMIGRATION("réincarnation / transmigration"),
    ROBOTS("robots"),
    ROMANCE("romance"),
    ROYALTY("royauté"),
    SAMURAI("samouraïs"),
    SCHOOL("ecole"),
    SCHOOL_LIFE("school life"),
    SCIENCE_FICTION("science-fiction"),
    SECRET_ORGANIZATIONS("organisations secrètes"),
    SHOJO_AI("shôjo-Ai"),
    SHONEN("shônen"),
    SINGING("chant"),
    SLICE_OF_LIFE("slice of life"),
    SORCERY("sorcellerie"),
    SPORT("sport"),
    SUPER_NATURAL("surnaturel"),
    SUPER_POWERS("super pouvoirs"),
    SURVIVAL("survie"),
    SURVEY("enquête"),
    TALES_AND_LEGENDS("contes et légendes"),
    TIME_TRAVEL("voyage temporel"),
    TORTURE("torture"),
    TOURNAMENTS("tournois"),
    TRAVEL("voyage"),
    VENGEANCE("vengeance"),
    VIDEO_GAMES("jeux vidéo"),
    VIRTUAL_WORLD("monde virtuel"),
    WAR("guerre"),
    WORK("travail"),
    WTF("wtf"),
    YOKAI("yōkai"),
    ;

    private val aliases = aliases.toSet()

    companion object {
        fun from(string: String): Genre? {
            return entries.find { it.aliases.contains(string.lowercase()) }
        }
    }
}
