[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="title" type="java.lang.String" --]
[#-- @ftlvariable name="description" type="java.lang.String" --]
[#-- @ftlvariable name="metrics" type="kotlin.collections.AbstractList<fr.shikkanime.dtos.MetricDto>" --]
[#-- @ftlvariable name="links" type="kotlin.collections.AbstractList<fr.shikkanime.entities.LinkObject>" --]
[#-- @ftlvariable name="platforms" type="kotlin.collections.AbstractList<fr.shikkanime.platforms.AbstractPlatform>" --]
[#-- @ftlvariable name="platform" type="fr.shikkanime.entities.enums.Platform" --]
[#-- @ftlvariable name="error" type="kotlin.NumbersKt" --]
[#-- @ftlvariable name="anime" type="fr.shikkanime.dtos.AnimeDto" --]
[#-- @ftlvariable name="simulcast_config" type="fr.shikkanime.platforms.configuration.PlatformSimulcast" --]
[#-- @ftlvariable name="episode" type="fr.shikkanime.dtos.EpisodeDto" --]
[#-- @ftlvariable name="episodeTypes" type="kotlin.collections.AbstractList<fr.shikkanime.entities.enums.EpisodeType>" --]
[#-- @ftlvariable name="langTypes" type="kotlin.collections.AbstractList<fr.shikkanime.entities.enums.LangType>" --]
[#-- @ftlvariable name="config" type="fr.shikkanime.dtos.ConfigDto" --]
[#-- @ftlvariable name="animes" type="kotlin.collections.AbstractList<fr.shikkanime.dtos.AnimeDto>" --]
[#-- @ftlvariable name="episodes" type="kotlin.collections.AbstractList<fr.shikkanime.dtos.EpisodeDto>" --]
[#-- @ftlvariable name="size" type="kotlin.NumbersKt" --]
[#-- @ftlvariable name="originalSize" type="java.lang.String" --]
[#-- @ftlvariable name="compressedSize" type="java.lang.String" --]