name: Check Playwright Version

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  check-and-update:
    name: Check and update Playwright version
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.actor == 'dependabot[bot]' && contains(github.head_ref, 'playwright'))
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Check Playwright version and update if necessary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #!/bin/bash

          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            # Extract version from PR title, e.g., "chore(deps): bump @playwright/test from 1.40.0 to 1.41.0"
            LATEST_VERSION=$(echo "${{ github.event.pull_request.title }}" | grep -oP '\d+\.\d+\.\d+' | tail -n 1)
          else
            LATEST_VERSION=$(npm view playwright version)
          fi

          CURRENT_VERSION=$(grep 'ARG PLAYWRIGHT_VERSION=' Dockerfile | awk -F'=' '{print $2}')

          echo "Current Playwright version: $CURRENT_VERSION"
          echo "Latest Playwright version from event: $LATEST_VERSION"

          if [ "$CURRENT_VERSION" == "$LATEST_VERSION" ]; then
            echo "Playwright version is already up-to-date in Dockerfile."
            exit 0
          fi
          
          echo "A new version of Playwright is available. Updating Dockerfile..."
          sed -i "s/ARG PLAYWRIGHT_VERSION=$CURRENT_VERSION/ARG PLAYWRIGHT_VERSION=$LATEST_VERSION/" Dockerfile
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            git add Dockerfile
            git commit --amend --no-edit
            git push origin HEAD:${{ github.head_ref }} --force
          else
            BRANCH_NAME="chore/update-playwright-version-${LATEST_VERSION}"
            git checkout -b "$BRANCH_NAME"
            git add Dockerfile
            git commit -m "chore(deps): bump Playwright to ${LATEST_VERSION}"
            git push origin "$BRANCH_NAME"
            gh pr create --title "chore(deps): bump Playwright to ${LATEST_VERSION}" --body "This PR updates the Playwright version to the latest stable release." --base master --head "$BRANCH_NAME"
          fi 