name: Delete old caches

on:
  schedule:
    - cron: '0 8 * * 1'  # Runs every Monday at 8:00 AM
  workflow_dispatch:

permissions:
  actions: write

jobs:
  delete_cache:
    name: Delete old caches
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: actions/github-script@v8
        with:
          script: |
            console.log("About to clear")
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            let i = 0
            for (const cache of caches.data.actions_caches) {
              console.log(cache)
              if (cache.ref != 'refs/heads/master' || (i > 0 && cache.key.includes('setup-java'))) {
                github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
              }
              if (cache.key.includes('setup-java')) {
                i++
              }
            }
            console.log("Clear completed")
