name: Global workflow

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Tests
        run: gradle clean test jacocoTestReport

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Cache gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-dev-dependencies-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-dev-dependencies-

  build:
    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Cache gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-dev-dependencies-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-dev-dependencies-

      - name: Build
        run: gradle clean installDist -x test

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: build/install/core
          key: ${{ runner.os }}-build-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-build-

  docker:
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm64/v8]

    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - uses: actions/checkout@v4

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: build/install/core
          key: ${{ runner.os }}-build-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker file
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: registry.ziedelth.fr:5000/shikkanime-core:dev
          platforms: ${{ matrix.platform }}

  clear_cache:
    runs-on: ubuntu-latest

    needs:
      - docker

    steps:
      - uses: actions/checkout@v4

      - name: Clear build cache
        uses: prantlf/delete-cache-action@v2
        with:
          key: ${{ runner.os }}-build-${{ hashFiles('**/build.gradle.kts') }}

      - name: Clear gradle cache
        uses: prantlf/delete-cache-action@v2
        with:
          key: ${{ runner.os }}-dev-dependencies-${{ hashFiles('**/build.gradle.kts') }}