name: Release workflow

on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.ziedelth.fr:5000
          username: ziedelth
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build docker file
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.ziedelth.fr:5000/shikkanime-core:latest