name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 10 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          reviewers: Ziedelth
          base-branch: dev
          target-branch: dev